export const message = {
  RESIGTER_SUCCESS: 'Resigter Successfully',
  RESIGTER_FAIL: 'Resigter Fail',
  SIGN_IN_SUCCESS: 'Login Successfully',
  SIGN_IN_FAIL: 'Login Fail',
  SIGN_UP_SUCCESS: 'Register Successfully',
  USER_NOT_EXISTS: 'User does not exist',
  USER_ALREADY_EXISTS: 'User already exists',
  USER_DELETE_SUCCESS: 'User deleted successfully',
  USER_CREATE_SUCCESS: 'User created successfully',
  USER_UPDATE_SUCCESS: 'User updated successfully',
  USER_UPDATE_Fail: 'User updated fail',
  PASSWORD_NOT_MATCH: 'Password does not match',
  FIND_USER_SUCCESS: 'Find users successfully',
  FIND_USER_FAIL: 'Find users fail',
  USER_NOT_ACTIVE: 'This user account is not active',
  CREATE_CATEGORY_SUCCESS: 'create category successfully',
  CREATE_CATEGORY_FAIL: 'create category fail',
  UPDATE_CATEGORY_SUCCESS: 'update category successfully',
  UPDATE_CATEGORY_FAIL: 'update category fail',
  DELETE_CATEGORY_SUCCESS: 'delete category successfully',
  DELETE_CATEGORY_FAIL: 'delete category fail',
  FIND_CATEGORY_SUCCESS: 'find category successfully',
  FIND_CATEGORY_FAIL: 'find category fail',
  CREATE_CATEGORY_DETAIL_SUCCESS: 'create category detail successfully',
  CREATE_CATEGORY_DETAIL_FAIL: 'create category detail fail',
  UPDATE_CATEGORY_DETAIL_SUCCESS: 'update category detail successfully',
  UPDATE_CATEGORY_DETAIL_FAIL: 'update category detail fail',
  DELETE_CATEGORY_DETAIL_SUCCESS: 'delete category detail successfully',
  DELETE_CATEGORY_DETAIL_FAIL: 'delete category detail fail',
  FIND_CATEGORY_DETAIL_SUCCESS: 'find category detail successfully',
  FIND_CATEGORY_DETAIL_FAIL: 'find category detail fail',
  CREATE_PRODUCT_SUCCESS: 'create product successfully',
  CREATE_PRODUCT_FAIL: 'create product fail',
  UPDATE_PRODUCT_SUCCESS: 'update product successfully',
  UPDATE_PRODUCT_FAIL: 'update product fail',
  DELETE_PRODUCT_SUCCESS: 'delete product successfully',
  DELETE_PRODUCT_FAIL: 'delete product fail',
  FIND_PRODUCT_SUCCESS: 'find product successfully',
  FIND_PRODUCT_FAIL: 'find product fail',
};
